name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  run-bun:
    name: Run test runner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Checkout Test Files
        id: checkout-test-files
        uses: actions/checkout@v4
        with:
          repository: c2pa-org/public-testfiles
          path: ./tests/fixtures/public-testfiles

      - name: Setup Bun
        uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76
        with:
          bun-version: latest

      - name: Install Dependencies
        id: bun-install
        run: bun install --frozen-lockfile

      - name: Run Tests
        id: bun-tests
        run: bun test --reporter=junit --reporter-outfile=junit-report.xml

      - name: Generate CTRF Report
        id: junit-to-ctrf
        run: bun x junit-to-ctrf junit-report.xml -o ctrf-report.json

      - name: Generate CTRF annotations
        id: ctrf-annotations
        run: bun x github-actions-ctrf ctrf-report.json
        if: always()
